---
version: 2
plan:
  project-key: TS
  name: TestName
  key: TN

stages:
  - First Build Stage:
      jobs: 
        - Build Ship Server

Build Ship Server:
  tasks:
    - script:
        - echo 'Hello world'
