---
version: 2
plan:
  project-key: TS
  name: TestName
  key: TN

stages:
  - First Build Stage:
      jobs: 
        - Build Ship Server 1
  - Second Build Stage:
      jobs:
        - Build Ship Server 2

Build Ship Server 1:
  tasks:
    - script:
        - echo 'Hello world'
        - echo 'Second tasks'

Build Ship Server 2:
  tasks:
    - script:
        - echo 'Hello world Ship Server 2'
        - echo 'Second tasks of Ship server 2'
---
version: 2
plan:
  project-key: MAR
  key: ROCKET
  name: Build the rockets

# List of plan's stages and jobs
stages:
  - Build the rocket stage:
    - Build

#Job definition
Build:
  tasks:
    - script:
        - mkdir -p falcon/red
        - echo wings > falcon/red/wings
        - sleep 1
        - echo 'Built it'
    - test-parser:
        type: junit
        test-results: '**/junit/*.xml' 
  # Job's requirements
  requirements:
     - isRocketFuel
  # Job's artifacts. Artifacts are shared by default.
  artifacts:
     - name: Red rocket built
       pattern: falcon/red/wings
