---
version: 2
stages:
  - Build the website:
      jobs:
        - Buildwebsite1
        - Buildwebsite2
  - Wait for confirmation:
      manual: true # Will await for execution by user
      jobs:
        - Waitforconfirmation1
        - Waitforconfirmation2
  - Clean afterwards:
      final: true # Will be executed even if previous results fail
      jobs:
        - Cleanafterwards1
        - Cleanafterwards2

Buildwebsite1:
  tasks:
    - script: |
        echo "Buildwebsite1"

Buildwebsite2:
  tasks:
    - script: |
        echo "Buildwebsite2"

Waitforconfirmation1:
  tasks:
    - script: |
        echo "Waitforconfirmation1"

Waitforconfirmation2:
  tasks:
    - script: |
        echo "Waitforconfirmation2"

Cleanafterwards1:
  tasks:
    - script: |
        echo "Cleanafterwards1"

Cleanafterwards2:
  tasks:
    - script: |
        echo "Cleanafterwards2"
