---
version: 2
triggers: []
plan:
  project-key: TESTFIRSTSPECS
  name: Test my first specs
  key: TN

stages:
  - Build the website:
      jobs:
        - Buildwebsite1
        - Buildwebsite2
  - Wait for confirmation:
      jobs:
        - Waitforconfirmation1
        - Waitforconfirmation2
  - Clean afterwards:
      jobs:
        - Cleanafterwards1
        - Cleanafterwards2

Buildwebsite1:
  tasks:
  - script:
      interpreter: SHELL
      file: scripts/test.sh
      argument: marcos alex

Buildwebsite2:
  tasks:
    - script: |
        echo "Buildwebsite2"

Waitforconfirmation1:
  tasks:
    - script: |
        echo "Waitforconfirmation1"

Waitforconfirmation2:
  tasks:
    - script: |
        echo "Waitforconfirmation2"

Cleanafterwards1:
  tasks:
    - script: |
        echo "Cleanafterwards1"

Cleanafterwards2:
  tasks:
    - script: |
        echo "Cleanafterwards2"
