---
version: 2
plan:
  project-key: TESTFIRSTSPECS
  key: BUIL
  name: BuildAnsibleDocker
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Build and Push ansible docker image
Build and Push ansible docker image:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: 'false'
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-docker-plugin:task.docker.cli
      configuration:
        commandOption: build
        repository: krakoslabs/comalatech-ansible:latest
        dockerfileOption: existing
        nocache: 'true'
        save: 'true'
        filename: comalatech-ansible:latest
        workingSubDirectory: dockers/ansible
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-docker-plugin:task.docker.cli
      configuration:
        commandOption: push
        username: dockerhubuser1
        password: BAMSCRT@0@0@ekfjdlkjfdlkjfldkjfdklfOI9/I921p/XeRKWKvQtgSHAL+No=
        pushRepository: krakoslabs/comalatech-ansible:latest
        registryOption: hub
        workingSubDirectory: dockers/ansible
triggers:
- polling:
    period: '180'
branches:
  create:
    for-new-branch: (release.*)
  delete:
    after-deleted-days: 7
    after-inactive-days: 30
  link-to-jira: false
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
